--Down Script
ALTER TABLE PersonGameList DROP CONSTRAINT FK_PersonID;
ALTER TABLE PersonGameList DROP CONSTRAINT FK_GameID;
ALTER TABLE PersonGameList DROP CONSTRAINT FK_ListKindID;


DROP TABLE [GamePlayListType];
DROP TABLE [PersonGameList];
DROP TABLE [Person];
DROP TABLE [Game];