--Down Script
ALTER TABLE GameList DROP CONSTRAINT FK_GameList_List;
ALTER TABLE GameList DROP CONSTRAINT FK_GameList_Game;
ALTER TABLE GameList DROP CONSTRAINT PK_GameList;

ALTER TABLE Person DROP CONSTRAINT FK_CompletedList;
ALTER TABLE Person DROP CONSTRAINT FK_WantToPlayList;
ALTER TABLE Person DROP CONSTRAINT FK_CurrentlyPlayingList;
ALTER TABLE UserList DROP CONSTRAINT FK_GameList_Person;


DROP TABLE [GameList];
DROP TABLE [UserList];
DROP TABLE [Person];
DROP TABLE [Game];