--Seed Script

--Inserting Sample Data for Game

INSERT INTO [Game] ([Title],[Description],[YearPublished],[AverageRating],[CoverPicture]) VALUES ('Gears Of War','The planet lies in ruin – cities crumbling, Man’s greatest works fallen. The Locust Horde has risen, and they won’t stop coming. They won’t stop killing. An inmate named Marcus Fenix, once left to die, is now charged with keeping humanity alive. He can take comfort in but one fact: The human race isn’t extinct. Yet.', 2006, 9.7, 'https://upload.wikimedia.org/wikipedia/en/thumb/8/82/Gears_of_war_cover_art.jpg/220px-Gears_of_war_cover_art.jpg');
INSERT INTO [Game] ([Title],[Description],[YearPublished],[AverageRating],[CoverPicture]) VALUES ('Deep Rock Galatic','Deep Rock Galactic is a cooperative first-person shooter video game developed by Danish studio Ghost Ship Games and published by Coffee Stain Publishing. ', 2018, 9.6, 'https://cf.geekdo-images.com/LlbizD6pMEMBm2pzYg8QVA__opengraph/img/GfwPOlMVJzcDDzzRtmaL0EVMB2Q=/fit-in/1200x630/filters:strip_icc()/pic6653293.jpg');
INSERT INTO [Game] ([Title],[Description],[YearPublished],[AverageRating],[CoverPicture]) VALUES ('Minecraft','If you can dream it, you can build it. Put your imagination and limitless resources to work with Creative Mode.', 2011, 9.5, 'https://image.api.playstation.com/vulcan/img/cfn/11307uYG0CXzRuA9aryByTHYrQLFz-HVQ3VVl7aAysxK15HMpqjkAIcC_R5vdfZt52hAXQNHoYhSuoSq_46_MT_tDBcLu49I.png');
INSERT INTO [Game] ([Title],[Description],[YearPublished],[AverageRating],[CoverPicture]) VALUES ('Dark Souls','Dark Souls focuses on dungeon exploring and the tension and fear that arise when players encounter enemies in this setting.', 2011, 8.5, 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8d/Dark_Souls_Cover_Art.jpg/220px-Dark_Souls_Cover_Art.jpg');
INSERT INTO [Game] ([Title],[Description],[YearPublished],[AverageRating],[CoverPicture]) VALUES ('Dark Souls 2','Join the dark journey and experience overwhelming enemy encounters, diabolical hazards, and the unrelenting challenge that only FROM SOFTWARE can deliver.', 2014, 4.5, 'https://upload.wikimedia.org/wikipedia/en/thumb/e/ed/Dark_Souls_II_cover.jpg/220px-Dark_Souls_II_cover.jpg');
INSERT INTO [Game] ([Title],[Description],[YearPublished],[AverageRating],[CoverPicture]) VALUES ('Dark Souls 3','As fires fade and the world falls into ruin, journey into a universe filled with more colossal enemies and environments. Now only embers remain… Prepare yourself once more and Embrace The Darkness!', 2016, 9.9, 'https://upload.wikimedia.org/wikipedia/en/thumb/b/bb/Dark_souls_3_cover_art.jpg/220px-Dark_souls_3_cover_art.jpg');
INSERT INTO [Game] ([Title],[Description],[YearPublished],[AverageRating],[CoverPicture]) VALUES ('BloodBorne','Hunt your nightmares as you search for answers in the ancient city of Yharnam, now cursed with a strange endemic illness spreading through the streets like wildfire. Danger, death and madness lurk around every corner of this dark and horrific world, and you must discover its darkest secrets in order to survive.', 2015, 9.9, 'https://upload.wikimedia.org/wikipedia/en/thumb/6/68/Bloodborne_Cover_Wallpaper.jpg/220px-Bloodborne_Cover_Wallpaper.jpg');
INSERT INTO [Game] ([Title],[Description],[YearPublished],[AverageRating],[CoverPicture]) VALUES ('Demon Souls','Embark on a dangerous journey to become the “Slayer of Demons”', 2020, 8.4, 'https://upload.wikimedia.org/wikipedia/en/thumb/9/91/Demon%27s_Souls_Cover.jpg/220px-Demon%27s_Souls_Cover.jpg');
INSERT INTO [Game] ([Title],[Description],[YearPublished],[AverageRating],[CoverPicture]) VALUES ('Elden Ring','Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.', 2021, 10, 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b9/Elden_Ring_Box_art.jpg/220px-Elden_Ring_Box_art.jpg');
INSERT INTO [Game] ([Title],[Description],[YearPublished],[AverageRating],[CoverPicture]) VALUES ('Xenoblade Cronicles','During an attack from the mechanical invaders known as the Mechon, Shulk discovers that he can tap into the full power of a mysterious blade known as the Monado.', 2010, 7.5, 'https://upload.wikimedia.org/wikipedia/en/d/d9/Xenoblade_box_artwork.png');
INSERT INTO [Game] ([Title],[Description],[YearPublished],[AverageRating],[CoverPicture]) VALUES ('Getting Over it','Getting Over It with Bennett Foddy is a punishing climbing game, a homage to Jazzuos 2002 B-Game classic Sexy Hiking.', 2017, 5.5, 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2e/Getting_Over_It_with_Bennett_Foddy.jpg/220px-Getting_Over_It_with_Bennett_Foddy.jpg');


